package util;

public enum View {
	HOME,
	MEMBER_LOGIN, NONMEMBER_LOGIN,
	MEMBER_JOIN, NONMEMBER_JOIN,
	RESERVE, RESERVATION,
	RESERVATION_UPDATE,
	RESERVE_DATE, RESERVE_TIME, RESERVE_CLASS, RESERVE_GUBUN, RESERVE_SHOW, 
	RESERVE_PLUS, MYLIST_SHOW, MYLIST_DEl, RESERVE_SEAT, MYLIST_UP,
	RESERVE_UPTIME, BEFORELIST_SHOW, LOGOUT
	
}
