package util;

public enum View { //이동할 메뉴 담기 
	HOME, MAIN, FREE_BOARD,
	MEMBER, MEMBER_SIGNUP, MEMBER_LOGIN, MEMBER_RESIGN,
	BOARD , BOARD_LIST , BOARD_DETAIL,	BOARD_INSERT ,	BOARD_UPDATE ,
	
}
